- hosts: localhost
  tasks:
  - name: install git
    yum: name=git state=latest
    become: yes
    become_method: sudo
  - name: clone myrepo
    git: repo=https://github.com/betsamee/myrepo.git dest=myrepo/
  - name: clone petclinic
    git: repo=https://github.com/betsamee/spring-petclinic.git dest=petclinic/
